In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.pipeline import make_pipeline
train=pd.read_csv("train.csv")
train=train.drop("id",axis=1)
test=pd.read_csv("test.csv")
test=test.drop("id",axis=1)
train

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Male,24.443011,1.699998,81.669950,yes,yes,2.000000,2.983297,Sometimes,no,2.763573,no,0.000000,0.976473,Sometimes,Public_Transportation,Overweight_Level_II
1,Female,18.000000,1.560000,57.000000,yes,yes,2.000000,3.000000,Frequently,no,2.000000,no,1.000000,1.000000,no,Automobile,Normal_Weight
2,Female,18.000000,1.711460,50.165754,yes,yes,1.880534,1.411685,Sometimes,no,1.910378,no,0.866045,1.673584,no,Public_Transportation,Insufficient_Weight
3,Female,20.952737,1.710730,131.274851,yes,yes,3.000000,3.000000,Sometimes,no,1.674061,no,1.467863,0.780199,Sometimes,Public_Transportation,Obesity_Type_III
4,Male,31.641081,1.914186,93.798055,yes,yes,2.679664,1.971472,Sometimes,no,1.979848,no,1.967973,0.931721,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20753,Male,25.137087,1.766626,114.187096,yes,yes,2.919584,3.000000,Sometimes,no,2.151809,no,1.330519,0.196680,Sometimes,Public_Transportation,Obesity_Type_II
20754,Male,18.000000,1.710000,50.000000,no,yes,3.000000,4.000000,Frequently,no,1.000000,no,2.000000,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
20755,Male,20.101026,1.819557,105.580491,yes,yes,2.407817,3.000000,Sometimes,no,2.000000,no,1.158040,1.198439,no,Public_Transportation,Obesity_Type_II
20756,Male,33.852953,1.700000,83.520113,yes,yes,2.671238,1.971472,Sometimes,no,2.144838,no,0.000000,0.973834,no,Automobile,Overweight_Level_II
20757,Male,26.680376,1.816547,118.134898,yes,yes,3.000000,3.000000,Sometimes,no,2.003563,no,0.684487,0.713823,Sometimes,Public_Transportation,Obesity_Type_II

In [2]:
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split
train,pretest=train_test_split(train,test_size=0.15,stratify=train["NObeyesdad"],
                               random_state=42)
validation=train["NObeyesdad"]

In [3]:
pretest

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
10672,Male,17.000000,1.800000,97.000000,yes,yes,2.000000,3.000000,Sometimes,no,3.00000,no,1.000000,1.000000,Sometimes,Public_Transportation,Overweight_Level_II
978,Male,32.749594,1.706741,102.003378,yes,yes,2.549782,1.818026,Sometimes,no,1.99467,no,1.103209,0.000000,no,Public_Transportation,Obesity_Type_II
3040,Female,21.000000,1.680000,68.000000,yes,yes,2.000000,3.000000,Sometimes,no,2.00000,no,1.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
3209,Female,16.198153,1.742850,53.699561,yes,yes,1.851262,1.000000,Sometimes,no,2.00000,no,0.168023,2.000000,Sometimes,Public_Transportation,Insufficient_Weight
13729,Female,18.000000,1.670000,60.000000,yes,yes,2.000000,4.000000,Sometimes,no,1.00000,no,0.000000,1.000000,Sometimes,Automobile,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18876,Male,22.000000,1.700000,80.000000,yes,yes,2.000000,3.000000,Always,no,2.00000,no,0.000000,1.000000,Sometimes,Public_Transportation,Overweight_Level_II
5304,Male,21.838323,1.722785,94.189167,yes,yes,2.000000,3.000000,Sometimes,no,2.00000,no,0.000000,1.281541,no,Public_Transportation,Obesity_Type_I
3566,Male,22.000000,1.850000,75.000000,yes,yes,2.000000,3.000000,Sometimes,no,1.00000,no,1.000000,0.000000,Sometimes,Automobile,Normal_Weight
1531,Female,18.000000,1.700000,50.000000,no,yes,3.000000,3.000000,Sometimes,no,2.00000,no,2.000000,2.000000,Sometimes,Walking,Normal_Weight
15409,Female,25.920738,1.668931,104.768318,yes,yes,3.000000,3.000000,Sometimes,no,1.48075,no,0.162279,0.912457,Sometimes,Public_Transportation,Obesity_Type_III

In [4]:
from sklearn.preprocessing import OrdinalEncoder
oencoder=OrdinalEncoder()
train_char=train.select_dtypes(include=[object]).drop("NObeyesdad", axis=1)
test_char=test.select_dtypes(include=[object])
pretest_char=pretest.select_dtypes(include=[object])

In [5]:
train_chararr=oencoder.fit_transform(train_char)
test_chararr=oencoder.fit_transform(test_char)
pretest_chararr=oencoder.fit_transform(pretest_char)

In [6]:
train_char=pd.DataFrame(train_chararr,columns=train_char.columns,
                        index=train_char.index)
test_char=pd.DataFrame(test_chararr,columns=test_char.columns,
                        index=test_char.index)
pretest_char=pd.DataFrame(pretest_chararr,columns=pretest_char.columns,
                        index=pretest_char.index)

In [7]:
from sklearn.preprocessing import StandardScaler
train_num=train.select_dtypes(include=[np.number])
test_num=test.select_dtypes(include=[np.number])
pretest_num=pretest.select_dtypes(include=[np.number])
sscaler=StandardScaler()

In [8]:
train_numarr=sscaler.fit_transform(train_num)
test_numarr=sscaler.fit_transform(test_num)
pretest_numarr=sscaler.fit_transform(pretest_num)
train_num=pd.DataFrame(train_numarr,columns=train_num.columns,index=train_num.index)
test_num=pd.DataFrame(test_numarr,columns=test_num.columns,index=test_num.index)
pretest_num=pd.DataFrame(pretest_numarr,columns=pretest_num.columns,index=pretest_num.index)
X=pd.concat([train_num,train_char],axis=1)
Y2=pd.concat([test_num,test_char],axis=1)
Y1=pd.concat([pretest_num,pretest_char],axis=1)

In [9]:
clf=GradientBoostingClassifier(n_estimators=100,learning_rate=1.0,
                              max_depth=1,random_state=0)
X

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,Gender,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,MTRANS
4347,-1.028710,-0.572393,-0.184699,-0.838694,-2.487930,-0.046192,0.025586,0.638220,0.0,1.0,1.0,2.0,0.0,0.0,2.0,3.0
832,2.663417,-1.372773,-0.298235,-0.838694,0.340017,1.598989,0.025586,-1.023928,0.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0
1709,0.226519,0.702717,0.946109,-1.335007,0.340017,0.139171,0.226540,-1.023928,1.0,1.0,1.0,2.0,0.0,0.0,1.0,3.0
14903,-0.501263,-0.915413,-0.752380,-0.838694,-2.487930,1.598989,0.025586,-1.023928,1.0,0.0,1.0,2.0,0.0,0.0,1.0,3.0
19371,0.369905,-1.203824,0.641669,1.038891,0.340017,0.689708,-1.115808,-0.337095,0.0,1.0,1.0,2.0,0.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12850,-0.501263,-0.597913,-0.721388,-2.595808,0.340017,0.279113,-0.201317,-0.698007,1.0,1.0,1.0,3.0,0.0,0.0,1.0,3.0
3584,-0.501263,-1.372773,-1.471442,-0.838694,0.340017,-0.046192,1.219125,0.638220,0.0,1.0,1.0,2.0,0.0,0.0,2.0,3.0
2005,-0.389449,0.068850,0.403533,-0.838694,-0.536859,-0.046192,0.138780,-1.023928,1.0,1.0,1.0,2.0,0.0,0.0,2.0,3.0
7226,-0.149632,-0.000692,-0.298235,-0.838694,0.340017,-1.691372,1.219125,0.638220,1.0,1.0,1.0,2.0,0.0,0.0,1.0,3.0
9551,-0.149632,0.227988,-0.298235,-0.838694,0.340017,-0.046192,-1.167952,2.300369,1.0,1.0,1.0,2.0,0.0,0.0,1.0,3.0

In [10]:
clf.fit(X,validation.values.ravel())

GradientBoostingClassifier(learning_rate=1.0, max_depth=1, random_state=0)

In [11]:
pretest

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
10672,Male,17.000000,1.800000,97.000000,yes,yes,2.000000,3.000000,Sometimes,no,3.00000,no,1.000000,1.000000,Sometimes,Public_Transportation,Overweight_Level_II
978,Male,32.749594,1.706741,102.003378,yes,yes,2.549782,1.818026,Sometimes,no,1.99467,no,1.103209,0.000000,no,Public_Transportation,Obesity_Type_II
3040,Female,21.000000,1.680000,68.000000,yes,yes,2.000000,3.000000,Sometimes,no,2.00000,no,1.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
3209,Female,16.198153,1.742850,53.699561,yes,yes,1.851262,1.000000,Sometimes,no,2.00000,no,0.168023,2.000000,Sometimes,Public_Transportation,Insufficient_Weight
13729,Female,18.000000,1.670000,60.000000,yes,yes,2.000000,4.000000,Sometimes,no,1.00000,no,0.000000,1.000000,Sometimes,Automobile,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18876,Male,22.000000,1.700000,80.000000,yes,yes,2.000000,3.000000,Always,no,2.00000,no,0.000000,1.000000,Sometimes,Public_Transportation,Overweight_Level_II
5304,Male,21.838323,1.722785,94.189167,yes,yes,2.000000,3.000000,Sometimes,no,2.00000,no,0.000000,1.281541,no,Public_Transportation,Obesity_Type_I
3566,Male,22.000000,1.850000,75.000000,yes,yes,2.000000,3.000000,Sometimes,no,1.00000,no,1.000000,0.000000,Sometimes,Automobile,Normal_Weight
1531,Female,18.000000,1.700000,50.000000,no,yes,3.000000,3.000000,Sometimes,no,2.00000,no,2.000000,2.000000,Sometimes,Walking,Normal_Weight
15409,Female,25.920738,1.668931,104.768318,yes,yes,3.000000,3.000000,Sometimes,no,1.48075,no,0.162279,0.912457,Sometimes,Public_Transportation,Obesity_Type_III

In [12]:
Y1ev=pretest["NObeyesdad"]
Y1=Y1.drop("NObeyesdad",axis=1)
preresults=clf.predict(Y1)

In [13]:
preresults
preresults=pd.DataFrame(preresults,columns=["NObeyesdad"])
preresults

               NObeyesdad
0     Overweight_Level_II
1         Obesity_Type_II
2      Overweight_Level_I
3     Insufficient_Weight
4           Normal_Weight
...                   ...
3109  Overweight_Level_II
3110       Obesity_Type_I
3111   Overweight_Level_I
3112  Insufficient_Weight
3113     Obesity_Type_III

[3114 rows x 1 columns]

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
from sklearn.metrics import accuracy_score
clf=GradientBoostingClassifier(n_estimators=100,learning_rate=0.75,max_depth=1,random_state=42)
clf.fit(X,validation)
preresults=clf.predict(Y1)
accuracy_score(preresults,Y1ev)

0.8651252408477842

In [56]:
results=clf.predict(Y2)
final=pd.DataFrame(results,columns=["NObeyesdad"])
id1=pd.read_csv("test.csv")
id1=pd.DataFrame(id1["id"],columns=["id"])
finalres=pd.concat([id1,final],axis=1)

In [57]:
finalres

          id           NObeyesdad
0      20758      Obesity_Type_II
1      20759   Overweight_Level_I
2      20760     Obesity_Type_III
3      20761       Obesity_Type_I
4      20762     Obesity_Type_III
...      ...                  ...
13835  34593  Overweight_Level_II
13836  34594        Normal_Weight
13837  34595  Insufficient_Weight
13838  34596  Insufficient_Weight
13839  34597      Obesity_Type_II

[13840 rows x 2 columns]

In [58]:
finalres.to_csv("Finalresult.csv",index=False)